### PR TITLE
Fix upload in richdocuments

### PR DESCRIPTION
**Pull request by MorrisJobke**
Ports https://github.com/owncloud/documents/pull/652 by @vicdeo to richdocuments

cc @pranavk @kendy @rullzer @Guillaume99 @mar1u5 

This fixes nextcloud/server#999

Also fixes this error message:

```
Could not find resource file "/apps/files/js/jquery.iframe-transport.js"
```

### CODE REVIEW

**Comment by nickvergessen** [comment]
@MariusBluem for the failed mention

**Comment by MorrisJobke** [comment]
> @MariusBluem for the failed mention

Oh ... nice :)

**Comment by MariusBluem** [comment]
> @MariusBluem for the failed mention

Sorry 😜 Wanted to do this - thought better yet than later 😁 

What about the `controller/documentcontroller.php` file?

**Comment by MorrisJobke** [comment]
> What about the controller/documentcontroller.php file?

This is not needed, because it was adjusted already ;)

**Comment by MariusBluem** [comment]
Works for me 👍

**Comment by timar** [comment]
Thanks!

**Pull request merged**
