### PR TITLE
Fix appid

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@VicDeo let's use this PR to fix travis ...

**Comment by DeepDiver1975** [comment]
````
Submodule path '3rdparty': checked out '8face268eb0db84b3a53b84f6c2a3d4ab555e615'

cp: cannot stat `../../documents/': No such file or directory

The command "bash ./before_install.sh documents $CORE_BRANCH $DB" failed and exited with 1 during .

**Comment by VicDeo** [comment]
@DeepDiver1975 errr. 
TBH part  of the code here is still related to old documents and should be annihilated.
To clean it I need to put off a new updater (and I don't like this idea)

**Comment by VicDeo** [comment]
@DeepDiver1975 Passing everywhere except Oracle VM
`sudo: must be setuid root`

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Passing everywhere except Oracle VM
> sudo: must be setuid root

as long as we test on oracle we have to stay on the legacy infra with travis

**Comment by VicDeo** [comment]
@DeepDiver1975 What action from my side is needed to fix failure on Oracle?

**Comment by DeepDiver1975** [comment]
sudo: true

In travis.yml

**Comment by VicDeo** [comment]
@DeepDiver1975 I tried that in https://github.com/owncloud/richdocuments/commit/37ce89fd56efce077404068c5245884ccf687a3c 
still no way

**Comment by DeepDiver1975** [comment]
hmmm ... looks like we have issues with oracle more generally - please disable oracle (and hhvm) for now and we merge this

**Comment by VicDeo** [comment]
@DeepDiver1975 

>Whats the reason for disabling coverage report?


```
The command "sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"" exited with 0.
1.04s$ sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
#!/usr/bin/env php
Uploading code coverage for repository "g/owncloud/richdocuments" and revision "eb119f49b326b62ef15674a8d7d7fa1654ba651c"... Failed
{"error":{"code":404,"message":"Not Found"}}
The command "sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"" exited with 1.
Done. Your build exited with 1
```

Source: https://travis-ci.org/owncloud/richdocuments/jobs/97239375

**Comment by DeepDiver1975** [comment]
Instead of disabling coverage we better setup this correctly on scrutinizer

**Comment by DeepDiver1975** [comment]
active now - https://scrutinizer-ci.com/g/owncloud/richdocuments

**Comment by VicDeo** [comment]
@DeepDiver1975 Thanks! Reenabled, the build is passing :dancers:

**Pull request merged**
