### PR TITLE
Change Richdocuments app name to Collabora Online

### PR DESCRIPTION
**Pull request by merttumer**

### CODE REVIEW

**Review by kulmann — APPROVED** [review]

**Review by JanAckermann — APPROVED** [review]
LGTM

**Comment by mmattel** [comment]
Q: does this have a docs impact?

**Comment by pmaier1** [comment]
> Q: does this have a docs impact?

No.

**Comment by JanAckermann** [comment]
Looking at: https://doc.owncloud.com/server/next/admin_manual/enterprise/collaboration/collabora_secure_view.html
there is nothing written about 'richdocuments'

**Comment by gokaysatir** [comment]
Hello :) Can we merge this one if it looks ok, thanks :)

**Pull request merged**
