### PR TITLE
[OC 10.6] Proper license fix

### PR DESCRIPTION
**Pull request by jvillafanez**
Requires https://github.com/owncloud/core/pull/37813 (planned for OC 10.6).
It might need an additional version change.

Minimum version of the app increased.

### CODE REVIEW

**Comment by jvillafanez** [comment]
CI is failing because OC 10.6 isn't out. Need to wait before retrying.

**Comment by micbar** [comment]
Core pr is merged.

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/37906 bumps the core version to 10.6.* - that should help CI here.

**Comment by jvillafanez** [comment]
Looks like the tests fail because of the missing EE license.
I think I can provide a config option to start the grace period for richdocuments. `richdocuments.startGracePeriod => false`. If it's set to true, the richdocuments app will try to start a grace period when it checks for the EE license.
This should help to pass the tests without requiring a license.

**Comment by jvillafanez** [comment]
```
latest: Pulling from owncloudci/core
Digest: sha256:f6e212069b57bcf2d3996317cc7fed4537465c0cb1dabf1ff12fe8495999c704
Status: Image is up to date for owncloudci/core:latest
$ wget -qO- https://download.owncloud.org/community/daily/owncloud-latest.tar.bz2 | tar -xj -C /tmp/owncloud/ --strip 1
Fetched 10.5.0 - channel: stable - build at 2020-08-03T07:16:07+00:00 - SHA: dc16af58beb6050976fd62bf683da0232034e1c6
```
core:latest doesn't seem very latest...

**Review by micbar — APPROVED** [review]

**Pull request merged**
