### PR TITLE
Implemented possibility of theming COOL.

### PR DESCRIPTION
**Pull request by merttumer**
Only possible color that can be sent to COOL
from the existing theme looks header bg color

Signed-off-by: Mert Tumer <mert.tumer@collabora.com>

### CODE REVIEW

**Comment by mrow4a** [comment]
@phil-davis can we restart CI here ?

**Comment by micbar** [comment]
@mrow4a Needs review?

**Comment by merttumer** [comment]
Yes review is appreciated :) thanks

**Review by mrow4a — APPROVED** [review]

**Comment by mrow4a** [comment]
@jnweiger merged fyi

**Pull request merged**
