### PR TITLE
make sure to retrieve correct supershare based on current dir context

### PR DESCRIPTION
**Pull request by mrow4a**
fixes https://github.com/owncloud/enterprise/issues/5729

### CODE REVIEW

**Comment by mrow4a** [comment]
@pako81 this is rather straighforward change , if you could have a look.

**Comment by pako81** [comment]
Code-wise looks good to me.

**Review by pako81 — APPROVED** [review]

**Comment by pako81** [comment]
Additionally, tested manually scenario described in https://github.com/owncloud/enterprise/issues/5729#issuecomment-1556702074 with this code in place and it works as expected: now share permissions are correctly evaluated 👍

**Comment by pako81** [comment]
@mrow4a is this dependent on a specific core version? @jnweiger we may need a new richdocuments app release (see https://github.com/owncloud/enterprise/issues/5729 for Customer's urgency).

**Comment by mrow4a** [comment]
works with current core version.

**Comment by jnweiger** [comment]
@mrow4a related compatibility question: will it explode when loaded in 10.11.0 or will it just work as "broken" as before?

**Pull request merged**
