### PR TITLE
[289] Fix app settings encryption message

### PR DESCRIPTION
**Pull request by mrow4a**
Fixes https://github.com/owncloud/richdocuments/issues/289

### CODE REVIEW

**Comment by jvillafanez** [comment]
I don't like the dependency with the encryption app module... any other alternative?

In addition, I think you're assuming that the app module will be enabled, what if there a different module enabled?

**Comment by mrow4a** [comment]
@jvillafanez any other ideas on how to achieve it? I could not find any other (actually this is copied from other place)

**Comment by jvillafanez** [comment]
> @jvillafanez any other ideas on how to achieve it? I could not find any other (actually this is copied from other place)

I've asked first! :sweat_smile: 

I can overlook this since it's copied, but I have to complain this isn't a good solution.

Why do we need to check for encryption in the first place? Why should the richdocument app care about encryption being enabled or not?

**Comment by mrow4a** [comment]
@jvillafanez this is related to the fact that Collabora/OnlyOffice/etc use "privileged" access to the files as they act on behalf of the user throught API - it means you need to login as editor (in case of normal and masterkey) or user incognito access (user key) - https://github.com/owncloud/richdocuments/blob/master/lib/Controller/DocumentController.php#L1084-L1119

some more read - https://github.com/owncloud/richdocuments/pull/260

**Comment by jvillafanez** [comment]
Ok, but this is a similar case that happens with the sharing, isn't it?
If userA shares a file with userB so he can edit the file, and the file is encrypted. I think userB can edit the file regardless of how it's encrypted (I might be wrong)

**Comment by mrow4a** [comment]
@jvillafanez it is about activity app in this issue https://github.com/owncloud/enterprise/issues/2619 . In user encryption I think sharing is even more complicated than that even with incognito mode.

**Comment by mrow4a** [comment]
@PVince81 is there a prettier way of checking for master/user encryption?

**Comment by PVince81** [comment]
ask @sharidas ^

**Comment by sharidas** [comment]
Check for user keys encryption or masterkey encryption finally reaches down to the appconfig.
So looking into the pr, the check for encryption enable looks ok to me, also the check for masterkey encryption looks ok to me. Regarding app dependency, I don't have insight over this app.

**Comment by jvillafanez** [comment]
If we're under time constraints I guess we'll have to use this fix. However, I think we should find a better solution.

I think core should somehow provide an API to transparently encrypt and decrypt the file regardless of what encryption app / mode / algorithm is used. This app shouldn't even care that the file will be encrypted. The FS should hide this complexity.

> @jvillafanez this is related to the fact that Collabora/OnlyOffice/etc use "privileged" access to the files as they act on behalf of the user throught API 

I still don't understand why. If I login a userA and edit a file, assuming that it will be collabora the one saving the file, it should send that userA is the one editing the file, and ownCloud should login with userA. For there, you just save the file normally. I don't know what I'm missing.

**Comment by jvillafanez** [comment]
> @jvillafanez how do you get a password of user A in user encryption for the file in an anynomous request from the editor server

Is the editor server the one performing the request, or the editor server redirects the browser? If the browser is redirected, I think cookies should be still valid and we can get the information we need from the session.
Is it possible to have a workflow like (?):
1. Login in ownCloud
2. Open the file. This will open it in the editor server
3. Edit and close.
4. The editor server redirects the browser to an ownCloud's url ("/apps/richdocuments/saveFile", for example)

I expect step 4 is performed by the browser with the previous cookies. This should work at least for common case, although there are several cases we should be careful about.

**Comment by mrow4a** [comment]
@jvillafanez I think we diverge from the purpose of this PR, but currently it is implemented as https://github.com/owncloud/richdocuments/blob/master/lib/Controller/DocumentController.php#L767-L773 - so this is a PublicPage and no user is logged in (and this is why we have tokens carrying user editor information https://github.com/owncloud/richdocuments/blob/master/lib/Controller/DocumentController.php#L783-L798, and this is why we have to login user to have activity app working https://github.com/owncloud/richdocuments/blob/master/lib/Controller/DocumentController.php#L1102-L1120). 

probably this is also useful explanation for @PVince81 and @sharidas

**Comment by mrow4a** [comment]
@DeepDiver1975 @jvillafanez added some more clarification comments while checking for server-encryption and for default encryption module app master-key (encryption app) being enabled

**Comment by micbar** [comment]
> @DeepDiver1975 @jvillafanez added some more clarification comments while checking for server-encryption and for default encryption module app master-key (encryption app) being enabled

Thank you.
User Key encryption and public pages is problematic.

Let us keep the scope of this PP

**Pull request merged**
